### ISSUE TITLE
Live-server starts and exits right away

### ISSUE THREAD

**Issue by cohenpts** [tapio/live-server#102]
I am having an Issue that live-server starts and exits right away, on CMD in Windows 7.
How do I keep the server running?﻿

**Comment by aadfPT** [comment]
Check if the port is already in use.

**Comment by pavel** [comment]
It should stay on, unless you have problems with executing `live-server`. Problems are reported in your `CMD`. Read them carefully and try to understand what's wrong. If you won't be able to understand the reason, post'em here.
