### ISSUE TITLE
Config file .live-server.json

### ISSUE THREAD

**Issue by intermundos** [tapio/live-server#105]
Where one finds the config file? If not present on my machine, should I create one? If so, how should it look like inside?

Thanks in advance.

**Comment by pavel** [comment]
It's not like you need to find it. You can create one in your `home` folder:
* Linux: `$HOME` or `~/`
* Windows: `%UserProfile%`

Here's an example of one:
```json
{
    "port": 8181,
    "host": "0.0.0.0",
    "root": "/public",
    "open": false,
    "ignore": "scss,my/templates",
    "file": "index.html",
    "wait": 1000,
    "mount": [
        ["/components", "./node_modules"],
        ["/image", "./myImageFolder"]
    ],
    "logLevel": 2
}
```

Executing `live-server` will use the options from the file above (if, of course, it is located in your home folder, and have the required name, which is `.live-server.json`). Specified options to `live-server` CLI program will override the ones in the file.

**Comment by pleerock** [comment]
Usually people use live-server for development purposes per project, so having to put `.live-server.json` in user directory does not make much of sense, rare people will use it this way. Instead live-server must read .live-server.json from the directory its being run or current project's root directory.

**Comment by JustinKubicek** [comment]
I agree @pleerock.
It about be located in the current directory where live-server is executed from.

If this was the case I could include it in my git repo for my project and all the members of my team could use the same configuration for the live-server.

**Comment by antonioaltamura** [comment]
I see this question is closed, but at the moment is there a way to make live-server read the config from the project root?

**Comment by orionrush** [comment]
TBH I assumed as many that placing the `.live-server.json` in the project root would do the trick. For a node project, Im not sure that having a simple server at root is as useful as one might like. I can spool up apache or larval valet for a quick file server. However being able to specify a simple server for a project to host demo files, I'd be very interested.
