### ISSUE TITLE
Opens sections of URL in different tabs

### ISSUE THREAD

**Issue by greduan** [tapio/live-server#11]
@tapio When I run `live-server` I get the following:

![2015-01-17-215248_1280x800_scrot](https://cloud.githubusercontent.com/assets/2314074/5791321/60e16b12-9e93-11e4-8413-45c5c3c32fdd.png)

To make it clear, they were opened in the same window but different tabs. I put it in different windows so that the URLs in each tab are clear.

I have Node v0.11.14 and `live-server` v0.6.3. I am running Arch Linux as my OS. Oh, and my browser is Firefox.

What could be causing this? Thanks! :)

**Comment by tapio** [comment]
Apparently this is an issue with "xdg-open" script in live-server's dependency library "node-open". There's an issue pwnall/node-open#7 which unfortunately isn't fixed, but seems to contain a work-around for Arch in the comments.

**Comment by Greduan** [comment]
Would this still apply if I'm using [mimi](https://github.com/march-linux/mimi) and I have already set it to handle `http` and `https` with Firefox?

```
x-scheme-handler/http: firefox
x-scheme-handler/https: firefox
text/html: firefox
```

Guess I'll report a bug there...

**Comment by tapio** [comment]
Current git master has `node-open` swapped to `opn` which is better maintained and probably does not have this bug. Feel free to reopen if the problem persists.
