### ISSUE TITLE
mount flag throwing Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by richarddavenport** [tapio/live-server#116]
Hopefully I'm just being dumb and am missing something. Can someone help me out?

OS X: 10.11.3
node -v: v5.10.1
npm -v: 3.8.3

*project structure:*
+node_modules
+src
&nbsp;&nbsp;⌞ +app
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⌞ app.js
&nbsp;&nbsp;⌞   index.html
package.json

*command*:
```
> ~/Code/Project/src
live-server --mount=/node_modules:../node_modules
/Users/richarddavenport/.npm-packages/lib/node_modules/live-server/live-server.js:82
	process.chdir(process.argv[2]);
	        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (/Users/richarddavenport/.npm-packages/lib/node_modules/live-server/live-server.js:82:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

Notice my cwd is in src not the root of the project. Thanks!

**Comment by tapio** [comment]
Hmm, there might be a problem mounting directories outside of server root. In any case, could you check that you are running the latest version of live-server (1.0.0) as that error location looks its from an older version.

**Comment by richarddavenport** [comment]
@tapio Yep, I'm dumb... I was on an older version. I could've sworn I was using 1.0.0, but obviously I was not. Anyways, all is working as expected! Love live-server, keep up the good work!
