### ISSUE TITLE
Problem ignore watching all typescript (.ts) files

### ISSUE THREAD

**Issue by jeud** [tapio/live-server#118]
I have `*.ts` in path `app` and the `app`'s sub directories which I want to ignore, or if I could **only watch** `public` and `app/templates` that's also fine too

I'm trying to everything I could think of but still not working so please help

*Terminal*
```
live-server --watch=public,app/templates
live-server --ignore=app/*.ts
live-server --ignore=app/**/*.ts
```

*`%UserProfile%`/.live-server.json*
```
{
    "port": 8080,
    "open": false,
    "watch": [
        "public",
        "app/templates"
    ],
    "ignorePattern": "*.ts",
    "wait": 1000
}

Nothing working for me now, please help.
```

**Comment by pavel** [comment]
The option `ignore` will not work, as it is intented to ignore specific files paths (no support for globbing).  
The option `ignorePattern` uses [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

In your case:
_Terminal/bash (escaping rules may vary depending on the terminal)_
```
live-server --watch=public,app/templates --ignorePattern=.*\\.ts
```
_%UserProfile%/.live-server.json_
```
{
    "port": 8080,
    "open": false,
    "watch": [
        "public",
        "app/templates"
    ],
    "ignorePattern": ".*\\.ts",
    "wait": 1000
}
```

**Comment by jeud** [comment]
@pavel Thanks
