### ISSUE TITLE
It does not work on PHP files

### ISSUE THREAD

**Issue by MDNCode** [tapio/live-server#124]
I have an HTML form that has action linked to PHP file.
I am able to live refresh HTML, but when the form jumps to PHP just blank.
Is there a workaround for PHP?

**Comment by gertcuykens** [comment]
Did you setup a proxy to your php server?

**Comment by MDNCode** [comment]
Sorry I am newbie.  Can you explain proxy?
All my files are on local desktop. I can launch and live-refresh HTML/ CSS files, but not PHP.  
PHP files cannot launch/open in live-server.

Another thing - is live-server secured?  Can someone has access to all my files on desktop using live-server?

**Comment by gertcuykens** [comment]
Start with something simple like setting up a normal php server first, recommend going to stackoverflow.com to get more help. A proxy can redirect your php urls to another server. Live server only does html not php.

**Comment by gunesh** [comment]
`"start": "node ./node_modules/live-server/live-server.js --open=uq/out/site/login.php --host=localhost --port=80 ",`

Above line serving PHP file but i am getting below error.
Error: listen EACCES 127.0.0.1:8081

PHP run in different port (WAMP Apache)
