### ISSUE TITLE
Can't start when installed locally

### ISSUE THREAD

**Issue by Mr-Binary** [tapio/live-server#132]
When installed globally, it works, but when installed locally

Error : No such file or directory

How to fix this? :)

**Comment by tapio** [comment]
Live-server is meant to be installed globally, but if you really need to use it locally, you need to use the full (relative) path to live-server.js file (`./node_modules/live-server/live-server.js`) as your shell does not know how to look stuff in random places. Of course you can use shell aliases, custom helper scripts or modify PATH to make this less tedious.

**Comment by Mr-Binary** [comment]
thanks 😀
