### ISSUE TITLE
Is this supposed to say "... that's being server"?

### ISSUE THREAD

**Issue by carloselhalabi** [tapio/live-server#140]
First, let me say: I really love this app. It really boosts my development. 

Now, when reading the [Usage from node](https://github.com/tapio/live-server/#usage-from-node) section, I find the following sentence confusing: 
`root: "/public", // Set root directory that's being server. Defaults to cwd.`
Shouldn't it say '... root directory that's being serveD.'? 

Since I'm not a native English speaker I was a little confused at first, but I'm convinced that it should say served.

**Comment by tapio** [comment]
Fix merged.
