### ISSUE TITLE
.live-server.json not working in windows

### ISSUE THREAD

**Issue by MrPhilbert** [tapio/live-server#144]
I created a  .live-server.json at the root of my project and added this:
var liveServer = require("live-server");

var params = {
	port: 80,
	root: "public",
	wait: 1000
};
liveServer.start(params);

When I start live-server, it still opens on port 8080 at the root (not public).
Apparently the .live-server.json file is not being read.
I'm using node 6.6.0 on windows 7.
Any ideas.
Thanks
Philbert

**Comment by pavel** [comment]
The file ` .live-server.json` should be in your home folder, not in the project's root.
See https://github.com/tapio/live-server#usage-from-command-line (below "Default options:" text).

**Comment by tapio** [comment]
As pavel hinted, project-specific (as opposed to user-global) config file is not yet implemented.
Also, `.live-server.json` is not a JavaScript file, but rather must be valid JSON, i.e. the contents should be:
```
{
"port": 80,
"root": "public",
"wait": 1000
}
```
