### ISSUE TITLE
Issue while loading accelerated mobile pages(AMP)

### ISSUE THREAD

**Issue by vineeshnp** [tapio/live-server#145]
Whenever an AMP page is served through live-server, its throwing an error. 
Upon inspection it's found that, the injected script is causing the issue. 
AMP is very strict in case of including other script in the page.
Can we have a parameter while booting the server so that no injection takes place.

Reference : 
https://www.ampproject.org/docs/get_started/create/basic_markup.html

**Comment by pavel** [comment]
If you exclude injected script, changes won't be propagated to the client. Or are you saying that you want to include "injected" part into your AMP page yourself, and prevent live-server from changing served files?

**Comment by vineeshnp** [comment]
Yup thats right. Blocking injection might impact performance. On the other hand, it can be added as an option so that in a case where injection of code causes issue. Like in AMP.

**Comment by pavel** [comment]
I don't understand you completely. Without injected part you go from `live-server` to `server`, no live updates will happen. From that point of view you can use `http-server` or a whole bunch of static web servers that are out there.
