### ISSUE TITLE
The browser loads, the page shows, but no reloading when I save the file

### ISSUE THREAD

**Issue by davestewart** [tapio/live-server#147]
That's pretty much it.

No errors, no logs, no console output.

```
[/Volumes/Data/Work/OpenSource/JavaScript/live-server-test]
Dave $ live-server
Serving "/Volumes/Data/Work/OpenSource/JavaScript/autoreloadserver" at http://127.0.0.1:8080
```

Then... nothing...

I'm on:

- OSX 10.10
- Node 6.7
- NPM 3.x

**Comment by davestewart** [comment]
So sorry - I got to the bottom of this - the quick HTML test file I was using only had a `<body>` tag, and no `<head>` so there was nothing for BS to hook into.

Stand down!

**Comment by tapio** [comment]
Live-server injects just before `</body>` tag. There used to be a warning if it is missing, but it was too spammy when e.g. including html fragments through AJAX, so it was moved to log level 3 (`--verbose`).
