### ISSUE TITLE
no need for python -m SimpleHTTPServer when we have http-server for node

### ISSUE THREAD

**Issue by Pomax** [tapio/live-server#15]
Given that most people will come here because they use node, recommending something like [http-server](https://www.npmjs.com/package/http-server) (installed like everything else with `npm install -g http-server`) probably makes more sense than to tell people to use Python's http server (also, remembering and typing out the Python command is a pain, whereas http-server is easy to remember and is a 'single' word =)

**Comment by tapio** [comment]
Python tends to be more readily available (e.g. installed by default on most Linux distros) than Node. If you are going to `npm install` something to get a tiny development server, might as well `npm install live-server` :smile:

**Comment by Pomax** [comment]
Python is only on linux and OSX. Node, on the other hand, is available on every computer for which live-server is getting installed. Also, you're saying what to install when live-server isn't enough. In that case, http-server (as a node technology) is guaranteed installable by every user that came here for live-server. Advocating Python, on the other hand, rules out a number of other platforms that don't have Python installed by default. So that's a bit silly =)

**Comment by tapio** [comment]
The thing is we **don't** know if people have Node installed. They can find live-server through a Google search and maybe not even have heard of Node.js, at which point they need to install node whether they'd like to use live-server or http-server. My rationale for giving that python example is a) given a random machine, I think there's a greater chance that python is installed than node (even now two years after I wrote the initial readme, but feel free to argue otherwise) and b) http-server example would be two lines and require additional install:

    npm install -g http-server
    http-server

(Still, maybe I'll add that as an alternative, or remove the thing altogether).

**Comment by Pomax** [comment]
my 2 cents there is that that's being needlessly confusing. While, indeed, they might find it through google, how are they going to install live-server without npm? And if they already use python and need a live server, why would they even bother with a node module instead of using `pip installed livereload`?

Basically I don't understand why you'd advocate using another scripting language when the only way to install live-server itself is to have node. Saying "if you don't have node, use Python", fair enough, but in this case the README says 'if you need *more*, use python', and that doesn't make sense =)

Also, don't undersell your userbase: you get hundreds of dowloads per week through npm - all those people have node ;)

**Comment by tapio** [comment]
> but in this case the README says 'if you need more, use python', and that doesn't make sense =)

Where did you get that? It says: "If you don't want/need the live reload, you should probably use something *simpler*, like the following Python-based one-liner:" (emphasis added)

> Also, don't undersell your userbase: you get hundreds of dowloads per week through npm - all those people have node ;)

Npm is pretty much the only way live-server is distributed, so naturally most downloads come from there. There is however no way of knowing how many of them needed to install node and npm just to get live-server. The thing I'm trying to say between the lines with the python one-liner is: If you just need a quick server and don't care about live reload, you already might have that if you have python, so you don't need to sweat about installing node and an additional package.

**Comment by Pomax** [comment]
hah, that's me totally misreading!
