### ISSUE TITLE
Add files to ignore watch

### ISSUE THREAD

**Issue by Mujaddadi** [tapio/live-server#151]
Hi,
    I am using grunt for my build and my folder structure is one "build" folder and one working folder. Every time I change anything in my main folder the live-server refreshes once and then again when the grunt build the files in my "build folder". So it refreshes total for two or three times. I want it to refresh only once for the working folder. So far I have done the following

- Change the options in live-server.js as follows

var opts = {
	host: process.env.IP,
	port: process.env.PORT,
	open: true,
	ignore: '/build', 
	mount: [],
	proxy: [],
	logLevel: 2
};

- Run the server with live-server --ignore=PATH"/build" command

I am not sure what I am doing wrong because nothing seems to work for me.

any solution ?

Thanks

**Comment by pavel** [comment]
Use `wait` option, as described [here](https://github.com/tapio/live-server#usage-from-node).

**Comment by pavel** [comment]
What version of `live-server` are you running?

**Comment by Mujaddadi** [comment]
version 1.1.0. I think it is the latest one

**Comment by pavel** [comment]
Is this how you run `live-server` from CLI?
```
 live-server --ignore=PATH"/build"
```

**Comment by Mujaddadi** [comment]
yes I tried that

**Comment by pavel** [comment]
That is wrong. **PATH** is not needed there, so the CLI usage would be: `live-server --ignore="build"`.

Also assuming you have the following project structure:
* project folder
  * work folder
  * build folder

Try running from CLI:
```
live-server work
```

**Comment by Mujaddadi** [comment]
Alright Fine. I will try that. Thanks

**Comment by pavel** [comment]
Welcome.
