### ISSUE TITLE
Live-server not loading js files

### ISSUE THREAD

**Issue by usman118591** [tapio/live-server#155]
I had recently installed live-server using npm. 
its working fine,but my js files are not loading in the server,can someone tell me what is the problem here?

**Comment by tapio** [comment]
Going to need some more information. "js files not loading in the server" - do you mean the auto-reload does not work or that the browser reports 404 when requesting them? In the latter case, check what you are using for the server root, as anything outside it will not be served. In case there's still problems, please post the command line you are using to launch live-server and the directory structure of your project.
