### ISSUE TITLE
Can't open index.php (shows folder)

### ISSUE THREAD

**Issue by Learn-Digital-Audio** [tapio/live-server#156]
Hello,

I have set-up a new Drupal 8 site on localhost which has index.php in the root. I am using XAMPP on Fedora. I am able to access the site perfectly by going to http://localhost/sites/ and opening the folder with the site inside.

On my other sites with index.html I type 'live-server' in the root directory and the page appears. With this Drupal site when doing the same I just get a directory inside Firefox. If I click index.php then I am prompted to save the file.

Any idea what's going on? I appreciate it's probably some misconfiguration on my end, so I am very grateful for any input!

**Comment by tapio** [comment]
Unfortunatelly live-server does not support PHP and it's not really planned either, apart from probably allowing proxying/rewriting php requests to a different server.

**Comment by Learn-Digital-Audio** [comment]
OK, cheers.

Can you recommend a replacement for working with PHP? It seems [http://livereload.com/](http://livereload.com/) is the most suitable for Linux and Drupal, but there are loads of different versions and they all seem to be slow on updates and requesting new maintainers on github :(

[https://github.com/guard/guard-livereload](https://github.com/guard/guard-livereload) < needs ruby that i don't know or care about
[https://www.npmjs.com/package/gulp-livereload](https://www.npmjs.com/package/gulp-livereload) < "If you are interested on maintaining this project, please let me know and I'll transfer the repo to you."
[https://www.npmjs.com/package/node-live-reload](https://www.npmjs.com/package/node-live-reload) < A mere 24 stars on Github!

I read somewhere browsersync has a million dependencies, and somewhere else it was not recommended for Drupal... so many opinions online, i am just trying to avoid spending an entire night making it work as great as live-server!
