### ISSUE TITLE
Browser Launch on Windows

### ISSUE THREAD

**Issue by IanNTFT** [tapio/live-server#157]
For our students we currently block access to the Command Prompt via setting the registry key HKCU\Software\Policies\Microsoft\Windows\System\DisableCMD but this also seems to stop live-server in atom launching a browser. Is there a way around this?
Thanks

**Comment by tapio** [comment]
We use https://github.com/sindresorhus/opn to launch the browser in cross-platform way, which seems to indeed call `cmd` on Windows. Perhaps you can ask the upstream for a fix?
