### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by nick-ChenZe** [tapio/live-server#159]
Hi, i have a problem when i use live-server.  When i start the server with command like `live-server path/to/index.html`. After typing the command, the page can be loaded, but resources look like in trouble. 
The error log in Chrome Dev Tool.
```javascript
Uncaught SyntaxError: Unexpected token <
```
Is there something wrong with in my way? Because i find no idea by googling it. Thank you!

**Comment by tapio** [comment]
If you use `live-server path/to/index.html` that means to use index.html as server root and not allow any other path to be fetched. Try `live-server path/to` instead.

**Comment by nick-ChenZe** [comment]
Thank you. It works!
