### ISSUE TITLE
Css changes does not show up in Google Chrome

### ISSUE THREAD

**Issue by elhoucine** [tapio/live-server#16]
I'm using Ubuntu 14.04 LTS and Google chrome Version 39.0.2171.99 (64-bit).

I'm using the editor and the navigator on the same screen, however when I change the CSS changes does not show up in the page *until I hover the mouse over it*.

It works fine in Firefox.

Do you have any idea why this is happening ?

Thanks.

**Comment by tapio** [comment]
See #5.
