### ISSUE TITLE
Using uuid instead of node-uuid?

### ISSUE THREAD

**Issue by marlun** [tapio/live-server#167]
When installing live-server I'm getting the following message:

    warning live-server > http-auth > node-uuid@1.4.7: use uuid module instead

Just a heads up.

Edit, sorry I see now that it's http-auth that maybe should update their code.

**Comment by marlun** [comment]
I'm sorry for the noice (should have looked before creating and closing the issue) but http-auth has a new version (3.1.1) which has updated to uuid instead of node-uuid. So I guess this is actually a heads up to you after all 😄

**Comment by tapio** [comment]
Deps updated.
