### ISSUE TITLE
Live Server instance does not shutdown after call to .close()

### ISSUE THREAD

**Issue by JohnAtFenestra** [tapio/live-server#169]
SUMMARY: I have a need to be able to shutdown a live server instance in a node application. My preliminary results have not been successful because calling close() on the returned server appears to not be successfully closing the server.

Live Server version 1.1.0 running on Atom 1.12.7.

# Current behavior

Calling `liveServer.start(...)` does the following:

1. Server starts on the given port
2. Call returns an instance of `http server`
3. Web page opens in the browser

However, calling `.close()` on the server instance does not stop the server. The server continues to respond to requests from the page. I have also attempted calling `liveServer.shutdown() ` with identical results.

# Background

I am working on a package for the Atom editor. The package is an enhancement of the existing atom-live-server package https://atom.io/packages/atom-live-server. The main enhancements are to show a list of servers, with their current status, and with the ability to stop any of the servers without closing Atom.

I have extracted the code for managing the live server into a small adapter. The following is the code I am currently working with. It is written in Coffeescript to simplify the handling of the calls to `allowUnsafeEval`:

```coffeescript

{allowUnsafeEval} = require 'loophole'
liveServer =  allowUnsafeEval -> require "live-server"


module.exports = class LiveServerAdapter
    constructor: (@port, @path) ->
        @server = undefined

    start: ->
        params = {
          port: @port,
          root: @path,
          open: true
        };

        allowUnsafeEval => @server = liveServer.start params;
        console.log('server started', @server)

    stop: ->
        console.log('stopping server', @server, @port, @path)
        if (@server)
            logger = () ->
                console.log('close callback invoked') # This is never called
            # liveServer.shutdown()
            allowUnsafeEval => @server.close(logger)
            console.log('*****************server stopped', @server)
            @server = undefined
```

A server instance is returned successfully by the call to `liveServer.start`. From my reading of the documentation at https://nodejs.org/api/net.html#net_class_net_server, all that should be necessary to stop the server is the call to `server.close()`. Per the instructions on that page, I have added a callback to verify that the operation was successful. The callback is not invoked.

Is there something obvious I might have missed as a step to shutting down a running live server instance?

**Comment by JohnAtFenestra** [comment]
I've solved this one myself. I'd like to leave a little bit of information in case anyone else runs into the same problem. 

# Solution

I found the solution at http://stackoverflow.com/questions/14626636/how-do-i-shutdown-a-node-js-https-server-immediately.

The issue is that the node http server will not close properly unless all the sockets have been destroyed. The solution is to store the sockets in an array as they are created and then to go through all the sockets when close is called, `.destroy()` them, and set that array index to `undefined`. Further, we trap any call to socket close and set the corresponding socket to `undefined` to prevent a double closure attempt.

My implementation is as follows (again in Coffeescript). Note that the `LiveServerAdapter` is instantiated one per port. 

# Code

```coffeescript
{allowUnsafeEval} = require 'loophole'
liveServer =  allowUnsafeEval -> require "live-server"

class SocketManager
    constructor: ->
        @resetSockets()

    addSocket: (socket) ->
        @$sockets.push(socket)
        socketId = @$sockets.length - 1
        socket.on 'close', () =>
            @$sockets[socketId] = undefined

    destroySockets: () ->
        killSocket = (socket) =>
            socket.destroy() if socket != undefined

        killSocket socket for socket in @$sockets
        @resetSockets()

    resetSockets: () ->
        @$sockets = []



module.exports = class LiveServerAdapter
    constructor: (@port, @path) ->
        @server = undefined
        @socketManager = new SocketManager()

    start: ->
        params = {
          port: @port,
          root: @path,
          open: true
        };

        allowUnsafeEval => @server = liveServer.start params;
        @server.on('connection', @connectionListener.bind(this))

    connectionListener: (socket) ->
        @socketManager.addSocket(socket)

    stop: ->
        if (@server)
            @socketManager.destroySockets()
            allowUnsafeEval => @server.close()
            @server = undefined
```

**Comment by tapio** [comment]
Thanks for writing the solution. This is something I feel would be part of `liveServer.shutdown()`'s job, though I don't like how much is involved in it. :/

**Comment by typhonrt** [comment]
This issue also caught me regarding graceful shutdown when embedding `live-server` in a Node app. 

There is an even simpler solution:
```
server = liveServer.start(options);
server.addListener('connection', (socket) => socket.unref());
```

Potentially this solution has much less overhead and could be added to `live-server`. Using chokidar and watching will keep alive `live-server` until `shutdown` is invoked. More info on [socket.unref()](https://nodejs.org/api/net.html#net_socket_unref)
