### ISSUE TITLE
default --https value for easy and quick https

### ISSUE THREAD

**Issue by PirtleShell** [tapio/live-server#170]
I was wondering if you'd consider a PR that allows a `--https` flag (i.e. without the `=module` bit) that sets the https module to the one found in `/test/conf`. It would allow for quick https setup right out of the box with only a few more lines of code.

I'd be happy to write the test and edit the necessary documentation.

It can be accomplished by adding 4 lines of code to the executable [just after the `--https=` flag](https://github.com/tapio/live-server/blob/master/live-server.js#L131):
```js
else if (arg.indexOf("--https") > -1) {
	opts.https = path.join(__dirname, 'test/conf/https.conf.js');
	process.argv.splice(i, 1);
}
```

**Comment by pavel** [comment]
I would like to avoid using public HTTPS certificate and key by default. This might hurt someone in future. I don't see a big hassle in generating your own keys and making a separate module for HTTPS.

**Comment by PirtleShell** [comment]
Alrighty, understood. If anyone finds this in the future and is interested, I have a public HTTPS certificate hosted on npm for plug-and-play capability: [live-server-https](https://www.npmjs.com/package/live-server-https).
