### ISSUE TITLE
Command-line option --port does not work

### ISSUE THREAD

**Issue by torarvid** [tapio/live-server#18]
Invoking as `live-server --port=8090` causes error:

    /usr/local/lib/node_modules/live-server/live-server.js:5
    	process.chdir(process.argv[2]);
    	        ^
    Error: ENOENT, no such file or directory

It seems like this is simply not implemented in the newest released version. I see that it *is* implemented in master, though... (But I at least was confused by the mismatch between the Readme and the latest npm release)

**Comment by tapio** [comment]
Well, the readme in the master branch follows what's implemented in the master branch. [Npm](https://www.npmjs.com/package/live-server) has the readme for npm version, as has the latest release tag. But still, I understand the confusion. I've been meaning to tweak some things with the new features as well as do some more testing and then release, but it hasn't happen. I'll try to get to that tomorrow or release the current master as is.

In the meantime, if you are on OSX or Linux, I suggest using `PORT=8090 live-server`. On Windows, you probably need to wrap that into a batch script: http://superuser.com/questions/544402/can-i-change-the-environment-on-a-per-process-basis-on-windows-like-on-unix
