### ISSUE TITLE
live-server injects HTML character references into JavaScript

### ISSUE THREAD

**Issue by i3games** [tapio/live-server#180]
See [https://gist.github.com/i3games/ea009e190e5bf80c0a7ea7994f1f136f](https://gist.github.com/i3games/ea009e190e5bf80c0a7ea7994f1f136f)

line 26 `	for (var i = 0; i &lt; sheets.length; ++i) {`
which results in a SyntaxError: missing ) after for-loop control

also
line 30 `	if (elem.href &amp;&amp; typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {`

**Comment by pavel** [comment]
OS: Linux
Browser: Chrome 55
Live-server: 1.2.0

With the same html file, live-server works without issue. Please, provide OS, browser + version, live-server version and Node.js version.

**Comment by i3games** [comment]
Sure, forgot: MacOS 10.11 El Capitan, Firefox 51.0.1, live-server 1.2.0, node 7.4.0.

What I do is: 

1. serve an [A-Frame](https://aframe.io/) scene (https://github.com/i3games/imperfect-vr/tree/master/01_hello_vr_world)[https://github.com/i3games/imperfect-vr/tree/master/01_hello_vr_world] with live-server
2. Change to The A-Frame Inspector CTRL-ALT-i and make changes to the scene
3. Save the scene from the Inspector ("Export to HTML"). The reason to save the file served with live-server is that I want to be able to open it later again with the A-Frame inspector.

**Comment by i3games** [comment]
Ah this seems to be a bug with the A-Frame Inspector. I think we can close it here.
