### ISSUE TITLE
how do I exit out of live-server from terminal?

### ISSUE THREAD

**Issue by gnohj** [tapio/live-server#182]
I've been using this for few weeks and its been great. But one annoying thing I found was that I have to manually exit out of the terminal to use the terminal- if that makes sense. Is there a command where I can disable live-server from running in terminal rather than manually closing it out every time?

**Comment by PirtleShell** [comment]
Use `Ctrl+C` or `Ctrl+D`. The first is a terminal's signal interrupter, the latter is the end-of-file signal; either should close down live-server for you. With that, you won't have to close out of the terminal to shutdown or restart the server.

**Comment by gnohj** [comment]
Thanks alot!

**Comment by duganchen** [comment]
I just tried Ctrl+D. It doesn't seem to work.
