### ISSUE TITLE
Running code when server has started

### ISSUE THREAD

**Issue by marlun** [tapio/live-server#187]
I want to use live-server when running my functional tests. I can do liveServer.start({...}) but how do I know that it has started and is listening for connections so that I can run my tests?

**Comment by pavel** [comment]
You can do that like so:
```javascript
var liveServer = LiveServer.start(liveServerOptions);
liveServer.on('listening', function () {
  // server is listening for connections
});
```

###### Please, close the issue if your problem is resolved.

**Comment by marlun** [comment]
My mistake was trying to do this on LiveServer directly instead of what's returned from start(), thanks!
