### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < myCode.js:1

### ISSUE THREAD

**Issue by alexandre1985** [tapio/live-server#188]
I have a simple html that loads a simple external javascript file and `live-server` can't seem to cope with that. It works when I view my index.html on Chrome with a double click, but when I use `live-server` to view the same file on localhost, I get this error on Chrome:

> Uncaught SyntaxError: Unexpected token <

Here is my `index.html`:
```html
<!DOCTYPE html>
<html>
<head>
	<title>My Awesome App!</title>
	<meta charset="utf-8">
</head>
<body>
	<div id="container"></div>
	<p>Hello</p>
	<script type="text/javascript" src="myCode.js"></script>
</body>
</html>
````

Here is my `myCode.js`:
```javascript
document.querySelector("#container").innerHTML = "Danny";
```
I'm using a Windows 10 machine and I have `live-server` installed globally and it's version is

> live-server 1.2.0

**Comment by pavel** [comment]
This should work without problems. The only way I can think of is that maybe `myCode.js` or any other `scripts` on your page contain `<` symbols.

**Comment by alexandre1985** [comment]
The files that I use are just this 2.
I have put them in this [repository](https://github.com/alexandre1985/test) for you to test

**Comment by pavel** [comment]
On:
* OS: Windows 10
* live-server: 1.2.0 (installed globally)

I've tried your files, and I can not reproduce the issue.
I ran `live-server` CLI inside the folder with those 2 files like this:
```
live-server
```
and I do not get any errors in Chrome dev console.

Can you, please, share your exact `live-server` CLI (or Node.js) usage?

**Comment by alexandre1985** [comment]
Very strange.
I also tried in my workplace machine that is a Debian and I also get the same error.
My node version is

> v7.7.1
My live-server version is

> live-server 1.2.0
On my Debian I can't see the exact node version right now, but is v.7.x.x

**Comment by alexandre1985** [comment]
I got the problem. As most of the time, it was found between the computer and the chair... ( = me).
I can't `live-serve` a file as argument, I have to use a directory instead.
Is that right?

**Comment by pavel** [comment]
Yes you're correct.

**Comment by alexandre1985** [comment]
I don't know how to mark issues with a label (as minor bug for example). Maybe you can.
As for the 'minor bug' maybe it could go even further and check if the argument is not a directory (then its a file) it could open the server with the directory of the file and then put the filename in the URL.
For example: if i did `live-server index2.html` live server would open a server in the directory of index2.html and then it would put on the url, for example, `localhost:8080/index2.html`.
If that was easy and possible it would be great since then I wouldn't need to live-serve a directory and change the url to point to the file (assuming the file is not index.html).
Thank you for the explanation and time ;)

**Comment by pavel** [comment]
Don't worry about labeling. Going further as you proposed is a possibility, but that makes things tangled.

If you want to open alternative path (like `index2.html` instead of `index.html`) you can use:
```
live-server --path=localhost:8080/index2.html
```
to make a browser open a different URL.

**Comment by alexandre1985** [comment]
Thank you, that was what I was looking for.
Everything is ok for me now. Should I close the issue or would you want it open for the minor bug issue?

**Comment by alexandre1985** [comment]
just to correct your code above. It should be:
`live-server --open=index2.html` without the localhost:8080.
I use this code for more completion:
`live-server --host=localhost --port=8080 --open=index2.html`

**Comment by pavel** [comment]
Thanks. Please, close this issue and create a new one with bug details (requesting to show error if the provided path is not a folder).
