### ISSUE TITLE
Spawn cmd ENNOENT - live-server won't open browser

### ISSUE THREAD

**Issue by romogo17** [tapio/live-server#190]
live-server **stopped opening the browser**. When I execute it in my command prompt I get the following error

`(node:456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn cmd ENOENT`

![capture](https://cloud.githubusercontent.com/assets/13739520/23684719/2323d104-0366-11e7-974f-3b52d2868253.PNG)

**Comment by pavel** [comment]
Please, provide following details:
* OS
* Browsers installed on the system
* Is `live-server` installed globally?

**Comment by romogo17** [comment]
1) My OS is Windows 10 Home

2) 
- Microsoft Edge
- Google Chrome
- Mozilla Firefox
- Internet Explorer

3) Yes it is!

--
I've tried uninstalling it and installing it again. As well as deleting the cache.
I don't know what might be causing this issue

**Comment by pavel** [comment]
Seems like a problem with [opn package](https://github.com/sindresorhus/opn).
Please, share the output of running this command:
```bat
set | findstr "^Path="
```
in Windows command line.

**Comment by romogo17** [comment]
I already fixed the issue. It seems like `C:\WINDOWS\system32` somehow was removed from the PATH
So a reinstalled the opn package, added `C:\WINDOWS\system32` to my path, restarted my computer and everything seems to be back to normal.

Thank you very much!

One more thing, what file should I modify to change the default port? 
8080 seems to be interfering with my Oracle DB instance and I'd rather not to have to shut it down

**Comment by pavel** [comment]
Add `--port` option to your CLI usage, .e.g.:
```bash
live-server --port=8081
```
See [CLI usage](https://github.com/tapio/live-server#usage-from-command-line) for more info.

###### Please, close the issue if your problem is resolved.

**Comment by abiodunDev** [comment]
@romogo17  am also having the same issues when am running my REACT 
![react_run](https://user-images.githubusercontent.com/50892994/59099940-7e25b200-891c-11e9-8971-339334089eb4.PNG)
and now i have installed npm install open how should add it C drive.

**Comment by Jaystar-Jay** [comment]
![IMG_20200608_173353](https://user-images.githubusercontent.com/58359459/84056733-8a6ca100-a9ae-11ea-8592-a791c9e4be30.jpg)


![IMG_20200608_173328](https://user-images.githubusercontent.com/58359459/84056750-8f315500-a9ae-11ea-869c-ecf49d5b0538.jpg)

These are the errors I got after successfully installing the live-server.

On checking the path, I will saw the xampp which I have deleted long time ago, this really gives me headache. Please help

**Comment by gaurpiyush001** [comment]
> Seems like a problem with [opn package](https://github.com/sindresorhus/opn).
> Please, share the output of running this command:
> 
> ```batchfile
> echo %PATH%
> ```
> 
> in Windows command line.

plz help me i am getting an error


Serving "C:\Users\gaurp\OneDrive\Desktop\Advanced CSS projects\advanced-css-course\Natours\starter" at http://127.0.0.1:8080
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd',
  path: 'cmd',
  spawnargs: [ '/c', 'start', '""', '/b', 'http://127.0.0.1:8080' ]

**Comment by anujktyagi** [comment]
Most likely issue with opening the browser. Use this option instead: 
_live-server dist --port=3000 --no-browser_
