### ISSUE TITLE
how to ignore certain file extensions

### ISSUE THREAD

**Issue by jurt** [tapio/live-server#197]
PLease explain how to ignore extensions like i.e  *.jade or *.scss ? 

 Your docs say that **--ignorePattern=RGXP** is deprecated. 
I tried ```--ignore="*\.scss,*\.css\.map,*\.ts,*\.sh"```, but to no avail.
```--ignore``` , as per docs, seems to only accept PATH, but is anymatch -compatible, but  anymatch also accepts extensions.

**Comment by donmccurdy** [comment]
+1; the `--ignore` flag seems to be having no effect.

**Comment by devinrhode2** [comment]
Docs need some updating.. see: https://github.com/tapio/live-server/issues/178
@tapio @pavel this can be closed
