### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by martindevans** [tapio/live-server#2]
Running

> npm install-g live-server

Results in a 404 error:

> npm ERR! fetch failed https://registry.npmjs.org/live-server/-/live-server-0.6.0.tgz
> npm ERR! Error: 404 Not Found

**Comment by smezae** [comment]
I have a poblem trying to install live-server on Mac OS High Sierra. I have tried to install it with npm and yarn and without warnings or errors...all good,all green, but when i type live-server -v command, it shows this:

`zsh: command not found: live-server`

npm version 5.6.0
yarn version 1.7.0
node version 8.11.2

Any idea?
