### ISSUE TITLE
atom live server

### ISSUE THREAD

**Issue by smackazi** [tapio/live-server#204]
please how can i change my live server default browser to chrome??????

**Comment by MatheusMcNeil** [comment]
Just change make Chrome your default browser.

**Comment by smackazi** [comment]
Thanks alot MatheusMcNeil

**Comment by chrdollar4** [comment]
Dose it means "--browser chrome" will not work? I got "--browser firefox" working but not Chrome. I am in Mac environment.

**Comment by tapio** [comment]
The right name for the browser executable depends on the platform, for example on Ubuntu, chrome seems to be `google-chrome`. I don't have a mac, but by googling, you might want to try `--browser Google\ Chrome` or if that doesn't work, perhaps some of the full path variants here: https://stackoverflow.com/questions/31083901/how-to-find-the-executable-file-for-open-command-in-mac
