### ISSUE TITLE
Page refresh problem

### ISSUE THREAD

**Issue by turkishdeveloper** [tapio/live-server#207]
I am using osx el capitan (10.11.6)
i am running this code : `live-server ./ --quiet --no-browser --port=8888` on Terminal but page still refreshing.

How can i stop refreshing page.

**Comment by tapio** [comment]
The whole idea of `live-server` is to refresh page on source changes, so no option currently disables that (`--quiet` suspends console output and `--no-browser` suspends launching a browser window). If you just want a regular web server, there are a lot of those, e.g. the following Python-based one-liner: `python -m SimpleHTTPServer`
