### ISSUE TITLE
localIP instead of 127.0.0.1 

### ISSUE THREAD

**Issue by suncn** [tapio/live-server#210]
i want to visit html on mobile, so i modify index.js like this
`LiveServer.server = server;

		var os=require('os'),
        iptable={},
        ifaces=os.networkInterfaces();
				
    for (var dev in ifaces) {
        ifaces[dev].forEach(function(details,alias){
            if ((details.family=='IPv4') && (details.internal == false)) {
                // iptable[dev+(alias?':'+alias:'')]=details.address;
                iptable['localIP'] = details.address;
            }
        });
    }

		var address = server.address();
		var serveHost = address.address === "0.0.0.0" ? iptable.localIP : address.address;
		var openHost = host === "0.0.0.0" ? iptable.localIP : host;

		var serveURL = protocol + '://' + serveHost + ':' + address.port;
		var openURL = protocol + '://' + openHost + ':' + address.port;`

can you add more options in config in .atom-live-server.json ? thank you.

**Comment by tapio** [comment]
The default option for the address, "0.0.0.0" should already make the html accessible from any ip that leads to your computer, so as long as you know your computer's IP (from e.g. command `ipconfig`) or the domain address (if you have one) it should work without enumerating and binding to a specific one.

**Comment by suncn** [comment]
ok, usually  i don't find my computer's ip and i just visit the computer by scanning the link.
