### ISSUE TITLE
Why npm live-server doesn't see file changes?

### ISSUE THREAD

**Issue by UArtur** [tapio/live-server#214]
## Software details

* OS: W10
* Browser (Latest Chrome, Opera, Firefox.):
* Node.js version:  6.11.2
* `live-server` version: 1.2.0

**Comment by tapio** [comment]
Sorry for a late response. I tried it just now with Windows 10 and Chrome and seems to be working fine. If the issue persists, could you post the command line you are using to launch live-server as well as the folder path you are launching from?

**Comment by nobuzz** [comment]
Same issue. Same environment. Using powershell.

Command line: PS C:\Users\Valerian\dev\public> live-server

**Comment by thinkong** [comment]
I had this problem.. found out that it won't work without a head/body tag.. are you sure you have one?

**Comment by UArtur** [comment]
It's working only when I change  Shell path in WebStorm to "C:\Program Files\Git\bin\sh.exe" -login -i ( MINGW64 bash now) --> (  https://stackoverflow.com/questions/30090800/how-to-open-a-terminal-on-webstorm  )
With Shell path in WebStorm "cmd.exe" which is default, it's not working (Microsoft Windows [Version 10.0.10586]).

**Comment by UArtur** [comment]
I've test out (cmd, bash, powershell) the problem was in the folder path that I launched from. FOLDER PATH need to contain only LATIN.

**Comment by Shivendra30** [comment]
Here is the path where live-server is stored on my PC - C:\Users\Ienovo\AppData\Roaming\npm\node_modules\live-server

I am using bash shell. Cannot understand what problem is there

**Comment by Half-empty-urlsession** [comment]
> Sorry for a late response. I tried it just now with Windows 10 and Chrome and seems to be working fine. If the issue persists, could you post the command line you are using to launch live-server as well as the folder path you are launching from?





https://matthias-coherence.github.io/expropriation/
