### ISSUE TITLE
Post Method Not Allowed

### ISSUE THREAD

**Issue by Joyzen** [tapio/live-server#222]
## Issue description

when I got an JSON file by XHR in post method,it response a 405 error:method not allowed

## Software details

* OS: windows 10
* Node.js version:v6.11.3
* `live-server` version:vscode v2.2.1

**Comment by devSonicgirl** [comment]
I had the same problem.
Modify it like this. Then it is possible temporarily.

index.js - 42 Line
if (req.method !== "GET" && req.method !== "HEAD") return next();
===>
if (req.method !== "GET" && req.method !== "POST" && req.method !== "HEAD") return next();

**Comment by Joyzen** [comment]
yes,it works!!!

**Comment by r03ert0** [comment]
it works great! It would be awesome if this simple patch were merged! a PR @devSonicgirl :p?
