### ISSUE TITLE
Odd 404 file behavior

### ISSUE THREAD

**Issue by LWTechGaming** [tapio/live-server#225]
## Issue description

This is more of a question/request for clarification than a bug report. When setting the 404 file programmatically, there seems to be a weird discrepancy in the process. If one uses a path relative to the server JavaScript file (In this located in the project root, and the 404.html file is in `./public`), the 404 page will not be displayed. However, if the file path is set relative to the docroot (In this case `./public`), it will work correctly.

Examples:
```js
file: './public/404.html' // Path relative to server file, does not work
// However...
file: '404.html' // Path relative to the docroot, works correctly
```
If this is intended behavior, then I'd like a clarification in the README concering this particular parameter 😄 

## Software details

* Command line used for launching `live-server`: None, programmatic launching
* OS: Windows 10 Pro 64-bit
* Browser (if browser related): None
* Node.js version: 6.9.1
* `live-server` version: 1.2.0

**Comment by tapio** [comment]
I'm going to say this is intended behaviour to encourage having the 404 page actually accessible to be served. I added a clarification.
