### ISSUE TITLE
Run php files with live-server possible?

### ISSUE THREAD

**Issue by MattiaVorstenbosch** [tapio/live-server#232]
As the title suggests. Can we run php files with this live-server?

I've been using it for static html pages fine and it works great!
However a php based project won't work as expected. It downloads the files locally instead of running them in the browser.

**Comment by Jackbennett** [comment]
No you need to have PHP the program available to process those files. Look into [XAMPP](https://www.apachefriends.org/index.html)

To keep livereload doing its thing, instead of xampp you might be able to use this as a middleware option https://www.npmjs.com/package/node-php

**Comment by cagcak** [comment]
@Jackbennett  is right, you need a middleware for this @MattiaVorstenbosch . But if you can use terminal like bash, you can always serve your php files with `php -S 127.0.0.1:8080` command line.

**Comment by mfgamboa85** [comment]
@cagcak how would that be? I have the same problem and I can't find the way out. I've already installed both php.cgi and node-php. Now I'm lost

**Comment by AndreyChursin** [comment]
php -S 127.0.0.1:8080 ! its good idea! 
in my case php -S 127.0.0.1:5500
