### ISSUE TITLE
Unable proxy to the HTTPS-enabled website

### ISSUE THREAD

**Issue by doggy8088** [tapio/live-server#250]
## Issue description

When I try to proxy a HTTPS-enabled website, it just can't navigate any page.
![image](https://user-images.githubusercontent.com/88981/38696225-2460dce6-3ec1-11e8-9beb-3b19d868209c.png)

## Software details

* Command line used for launching `live-server --proxy=/:https://uaptc.azurewebsites.net`:
* OS: Windows 10 (Version 10.0.16299.371)
* Browser (if browser related): Chrome 65
* Node.js version: v9.11.1
* `live-server` version: 1.2.0

**Comment by guysoft** [comment]
You need to enable websockets in your proxy, something like this:
https://github.com/guysoft/nginx-proxy-pass-docker/commit/24f7801d8c9f1969f3b6e71b19fff352b1d6e402

**Comment by KingMario** [comment]
@doggy8088 You may try this: NODE_TLS_REJECT_UNAUTHORIZED=0 live-server --proxy=/:https://uaptc.azurewebsites.net
