### ISSUE TITLE
The colors package breaking npm test

### ISSUE THREAD

**Issue by doggy8088** [tapio/live-server#252]
## Issue description

The [colors](https://www.npmjs.com/package/colors) package breaking `npm test` on Windows.

![image](https://user-images.githubusercontent.com/88981/38700940-33795d80-3ecf-11e8-8aa3-114246814d1a.png)

## Software details

* Command line used for launching `live-server`:
* OS: Windows 10 (Version 10.0.16299.371)
* Browser (if browser related): Chrome 65
* Node.js version: v9.11.1
* `live-server` version: 1.2.0

**Comment by tapio** [comment]
This is now finally fixed.
