### ISSUE TITLE
0.0.0.0

### ISSUE THREAD

**Issue by giltig** [tapio/live-server#26]
Hi,
the new version of live-server directs automatically to 0.0.0.0 instead of localhost (127.0.0.1)

**Comment by tapio** [comment]
This was changed in PR #8, to fix problems mentioned in #7. Can you elaborate on why it's a problem?

**Comment by giltig** [comment]
I get page not found on windows when using liveserver

**Comment by tapio** [comment]
Is it only the browser URL? I.e. if you manually navigate to 127.0.0.1:8080 does it work?

**Comment by tapio** [comment]
Master branch now launches the browser to 127.0.0.1 instead of 0.0.0.0. I'll update npm soon. Let me know if there are still problems.
