### ISSUE TITLE
NPM version does not match Github.

### ISSUE THREAD

**Issue by TJHdev** [tapio/live-server#267]
I've been looking into issue #264. And through running my globally installed version of live-server for debugging vs the one I have downloaded from git I have noticed some discrepancies. 

I was going to try and fix the bug myself but it seems the code from github is correct and working. NPM simply needs updating to match.

## Software details

Line 361 from the git hub repo of 1.2.0 shows the following code:
**var cssChange = path.extname(changePath) === ".css" && !noCssInject;**

Line 346 of the globally installed npm version has the following code:
**var cssChange = path.extname(changePath) === ".css";**

* Command line used for launching `live-server`:
* OS: Windows 10
* Browser (if browser related): Chrome
* Node.js version: 10.4.0
* `live-server` version: 1.2.0

**Comment by tapio** [comment]
Well Github has the development version so it's expected to have differences to npm version until a new release is made. However, this time some changes were needlessly long just sitting there. Version 1.2.1 with latest changes is now published in npm.
