### ISSUE TITLE
event-stream@3.3.6 contains malicious code, pin to 3.3.4?

### ISSUE THREAD

**Issue by nennes** [tapio/live-server#285]
According to this:
https://github.com/dominictarr/event-stream/issues/116

It looks like a bad actor has injected malicious code to event-stream@3.3.6 and bumped it to 4, so that all minor version upgrades end up with the malicious code.

`live-server` is using `event-stream@latest`, shall we specify a safe version?

Happy to raise a PR where I'm locking event-stream to 3.3.4.

**Comment by tapio** [comment]
I made it use 3.3.4 for now. Also updated other dependencies and published version 1.2.1.

**Comment by nennes** [comment]
Thanks for taking action so quickly! Closing the issue.
