### ISSUE TITLE
Event Stream Version Has Security Vulnerabilities

### ISSUE THREAD

**Issue by FarajiA** [tapio/live-server#286]
## Issue description
Hey folks, it looks like the version of Event Stream you're using as a dependency has a dependency flatmap-stream that is malicious. Updating Event Stream to v4 would be best.

Thanks!

## Software details

* Command line used for launching `live-server`:
* OS:
* Browser (if browser related):
* Node.js version:
* `live-server` version: 1.2.1

![event-streamversion](https://user-images.githubusercontent.com/5041718/49167363-d7bc7c80-f2fa-11e8-9f0f-c9607f49d44f.png)

**Comment by vogloblinsky** [comment]
Seems fixed by this commit and last release 1.2.1
