### ISSUE TITLE
[FEATURE] SASS/Coffeescript Support

### ISSUE THREAD

**Issue by willrstern** [tapio/live-server#3]
I could see this utility having a great niche as the zero-config dev environment.

A very useful feature would be `live-server --sass` or `live-server --coffee`
- live-server auto-complies code from any /sass directory to a neighboring /css directory
- same with coffee, any /coffee directory to a neighboring /js directory

**Comment by famousgarkin** [comment]
There's enough options available to watch and rebuild assets in parallel with running live server. Please keep live server simple and focused, don't turn it into another Grunt/Gulp/webpack/whatever plugin and configuration do-it-all craziness.

**Comment by nikolaswise** [comment]
@famousgarkin +1

**Comment by 1j01** [comment]
(-1) @famousgarkin +1
Just run the live-server at the same time as whatever compilers/watchers/build tools.

**Comment by harrytruong** [comment]
:+1: @famousgarkin, I agree. Those asset tools should be run separately to live-server. 

For example, my working setup involves SASS and I run `node-sass` via CLI to meet my needs. When I make changes, my sass is compiled into css, which triggers a nice reload by `live-server`. 

---

Tips for anyone using `node-sass` in combination with `live-server`:
 1. Always install `live-server` and `node-sass` as local dev dependencies to your project. This ensures you'll always have these tools frozen and stable for your project:  

  ```bash
  $ npm install live-server node-sass --save-dev
  ````
 2. Running `node-sass` (assuming input of `css/sass/style.sass`, and output of `css/style.css`):

  ```bash
  $ ./node_modules/.bin/node-sass -w css/sass/style.scss -o css --source-map=true --output-style=compressed
  ```
  **Note:** `node-sass` catches changes from within the @import file calls, which is great.

 3. Running `live-server`:

  ```bash
  $ ./node_modules/.bin/live-server --no-browser --ignore=css/sass,css/style.css.map
  ```
  **Note:** `live-server` reloads when your `sass` files changes, but this isn't ideal. It should ignore those changes until `node-sass` finishes compiling the `css/style.css` file. I'm using the `--ignore` flag here, but this feature is pending PR https://github.com/tapio/live-server/pull/48.

 4. To bring it all together, you can add a clean custom script to your `package.json` file:

  ```js
  {
    // ... package.json metadata ...
    "scripts": {
      "dev-mode" : "./node_modules/.bin/node-sass -w css/sass/style.scss -o css --source-map=true --output-style=compressed & ./node_modules/.bin/live-server --no-browser --ignore=css/sass,css/style.css.map"
    }
  }
  ```

  Then to run both tools, it's just `npm run-script dev-mode`!
