### ISSUE TITLE
live-server starts but shows "Cannot GET /"

### ISSUE THREAD

**Issue by PippoApps** [tapio/live-server#301]
## Issue description
It used to work perfectly. Browser shows "Cannot GET /".
Console error is: "**Failed to load resource: the server responded with a status of 404 (Not Found)**". It seems resource name is empty "".
This happened after I had some windows related problems and had to restore some system files. Reinstalled node, npm and live-server though. Does not work even on freshly created project.
There is no .live-server.json, it used to work out of the box with default settings.

## Software details

* Command line used for launching `live-server`:
live-server start
* OS: 
Windows 10
* Node.js version:
10.15.3
* `live-server` version:
1.2.1

**Comment by avalonabecker** [comment]
I had this issue, and had simply not added the dot to indicate a local directory, so my live server was looking for /public on my root dir, instead of the local project directory.

WAS:
var params = {
    port: 5000,
    root: "/public",
    open: true,
    file: "index.html",
    wait: 500,
    logLevel: 2,
};

FIXED
var params = {
    port: 5000,
    root: "./public",
    open: true,
    file: "index.html",
    wait: 500,
    logLevel: 2,
};
