### ISSUE TITLE
Not compatible with Visual studio 2013 debug

### ISSUE THREAD

**Issue by theWhiteFox** [tapio/live-server#35]
Love live server but when I try to debug in VS 2013 with this server on, I cannot.
My work around is to either turn off live server or debug in a different browser.

**Comment by tapio** [comment]
I don't have VS2013 and I have no idea how its debugging works. Have you tried if running live-server in a different port makes a difference? What browser are you using?

**Comment by Stevo5o** [comment]
Not sure would a change of port work. Basically in Powershell (cli) I live-server into the Visual Studio 2013 project folder.  c:/user/stephen/visualStudioProjects live-server , however once I do this VS 2013 will not open my project in debug mode (open in a browser). Browsers: I mainly use chrome and then firefox and maybe after that some IE

**Comment by tapio** [comment]
Is this still an issue with latest live-server? Trying with another port is easy, just launch live-server with `--port=12345` parameter. Also, when Visual Studio launches your project in debug, what URL does it open it to?

> however once I do this VS 2013 will not open my project in debug mode (open in a browser).

Is it just browser opening that does not work, or the whole debugger does not start (or exists immediately)? Any errors in Visual Studio output?
