### ISSUE TITLE
live-server does not detect a change in the JS file, and does not reload the page on Windows 10, when installed through NPM

### ISSUE THREAD

**Issue by Vedang-Mahajan** [tapio/live-server#358]
**Issue:** I installed live-server through the command - `npm install live-server -g`
It installed correctly but showed errors that said `chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.` and `fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.`
When I run the command - `live-server` in my project folder, it successfully opens my browser with the index.html file, but does not detect any changes in the JavaScript file, after it is saved, and does not reload the page.

**Software Details:**
Command-line used for launching `live-server`: Windows Command Prompt
OS: Windows 10, x64
Browser: Google Chrome Version 87.0.4280.66
Node.js version: v12.18.3
`live-server` version: v1.2.1

[Loom Video demonstrating the issue](https://www.loom.com/share/0df1b9e02fe54a7ab23bf01a45476210)

@tapio @mikker @kylecordes @davej @inadarei @dotnetCarpenter @leolower @Pomax @dvv @evanplaice @wmira @harrytruong @kavsingh @izeau @dpgraham @diego-vieira @psi-4ward @sakiv @richardgoater @carloselhalabi @gusgard @rahatarmanahmed @ajaysinghj8 @pavel @pmentz @mattymaloney @pirtleshell  Please help if you can. Forgive me if there is any mistake in this issue,  because I am publishing one for the first time.

**Comment by diego-vieira** [comment]
dude, just try another app, no need to spam everybody 

https://www.npmjs.com/package/http-server

**Comment by mikker** [comment]
Make sure that your `index.html` is a complete HTML doc with a `<head>` and `<body>` and everything. Otherwise `live-server` can't insert its JS.

Please don't mention every contributor to a project like this in the future.

**Comment by Vedang-Mahajan** [comment]
Very sorry if it was disturbing 😟. I'll make sure I don't spam from next time. Anyways, thanks for helping out!
