### ISSUE TITLE
Add a way to proxy some requests path

### ISSUE THREAD

**Issue by wmira** [tapio/live-server#36]
On some projects, it's useful to have the static files served by live-server and rest api calls be directed to a real server. This enable us to work with the static files on their own.  E.g. anything /api/ calls gets redirected to http://127.0.0.1:8181/ which will be technically a java ee server executed from Eclipse for example.

The reason this is useful because you don't want to work with the static files served by these as sometimes it takes 3 to 5x reload for you to get your updated javascript/css shown.

**Comment by harrytruong** [comment]
@wmira I think this is a good feature, but I don't have experience with what this would look like. There's a fork'd project [jspm-server](https://github.com/geelen/jspm-server) by @geelen that I think implements what you're looking for. 

I've reached out to see if we can get a PR from their work. Otherwise, you could look into submitting a PR of your own?

**Comment by wmira** [comment]
@harrytruong I have submitted a PR for this feature.

**Comment by harrytruong** [comment]
@wmira thanks for the PR. It's definitely appreciated. 

@tapio raised a good list of concerns with your PR, so we can't merge it as-is. However, I think you've given me more than enough to work with. When I get the chance, I'll clean up your PR for you, and have a clean PR to re-submit. 

---

As a side note: I'm surprised by your implementation. I actually thought you meant something else for the proxy feature. When I get the chance, I'll write up my version.

**Comment by tomwidmer** [comment]
Note that http-server implements this feature by just having a flag to make not-found paths always get forwarded to the proxy, e.g.:

    http-server -p 9090 -P http://localhost:8080

It doesn't support live-reload though...

**Comment by Industrial** [comment]
Hi. I'd really love to have this functionality, is there any chance to see it in the foreseeable future :-)?

**Comment by coreyog** [comment]
+1

**Comment by kylecordes** [comment]
This would be a *very* useful feature.

**Comment by moshemal** [comment]
+1
