### ISSUE TITLE
Upon running 'live-server', my terminal is spammed with Jargon.

### ISSUE THREAD

**Issue by xzntrc** [tapio/live-server#387]
Here's the image of it. 
![image](https://user-images.githubusercontent.com/96399844/148664438-65dc3d99-4c3e-42fd-8dba-e7a89a152888.png)
It look like some cringey virus code? spamming liberty?

**Comment by JavierDamico** [comment]
Same here

**Comment by Eccentrici** [comment]
It looks like some stupid viruses I've seen. Idk why it spams "Liberty". It looks like it's trying to spam ascii art? and then some jargon which lags a bit.

**Comment by Eccentrici** [comment]
Here we are: https://www.reddit.com/r/programming/comments/rz5rul/marak_creator_of_fakerjs_who_recently_deleted_the/

**Comment by Ionaru** [comment]
See https://github.com/Marak/colors.js/issues/285

**Comment by NAMIKAZEMINATO7** [comment]
Same problem here also I've been searching for solution for hours now. Don't know what is happening

**Comment by Offroaders123** [comment]
This is the solution I am currently using myself for Live Server, I originally commented it in the issue thread under Colors.js:
https://github.com/Marak/colors.js/issues/285#issuecomment-1007890688

**Comment by Offroaders123** [comment]
Here's the same comment I posted there, Mount as well copy it to this thread as well.

Alright, figured out how to temporarily fix the issue for use with Live Server.
The package.json for Live Server has Colors.js set to use the newest possible version available, latest, so I changed it back to the most recent Colors.js version that didn't have the issue, 1.4.0. Just thought I'd share a fix for anyone else that may also run into this too 👍

**Comment by Mohamed-Khaled-M** [comment]
comment the affected code.
![Screenshot 2022-01-09 115220](https://user-images.githubusercontent.com/57816764/148677416-989e589a-578d-4cdd-878e-077161577bb8.jpg)

**Comment by VirajMadhu** [comment]
> Here's the image of it. ![image](https://user-images.githubusercontent.com/96399844/148664438-65dc3d99-4c3e-42fd-8dba-e7a89a152888.png) It look like some cringey virus code? spamming liberty?

Same here. Finally, I removed live-server dependencies.

**Comment by belauzas** [comment]
Issue been solved #386, just waiting for an approval.

**Comment by belauzas** [comment]
If anyone is interested, I forked this project and fixed it. You can use is the same way as original one. Link: https://www.npmjs.com/package/dead-server
Good luck! ❤🚀🎅

**Comment by sultanofcardio** [comment]
As a quick fix, you can also just put `colors` directly in your `package.json` to override the live-server dependency

```json
{
  "dependencies": {
    "colors": "1.4.0",
    "live-server": "1.2.1"
  }
}
```

<img src="https://user-images.githubusercontent.com/14842108/148712738-30ea68a4-b0a1-45a8-b5f7-b084c0ea36e4.png" width="320">
