### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by DennisTimmers01** [tapio/live-server#39]
Hey, newb here.

So I installed everything like the guide told me to.
But I keep getting -bash: live-server: command not found.
I did googled about for a while and added a PATH to the .profile file.
That made it so that the command node does work, which it didn't at first either.
But still I can't get live-server to work.

I was hoping that anyone could help me with my problem.
Thank you in advance.

**Comment by tapio** [comment]
What did you add to the PATH? According to https://docs.npmjs.com/files/folders, npm symlinks globally installed executables to `/usr/local/bin`, you should also check  if `live-server` is actually present there and if not, find if node is installed with some other prefix than `/usr/local`.

**Comment by DennisTimmers01** [comment]
The prefix was wrong so I replaced the files manually to "/usr/local/bin" and that fixed the error.
Thank you very much :+1:
