### ISSUE TITLE
It doesn't reload on changes

### ISSUE THREAD

**Issue by proffapt** [tapio/live-server#399]
## Issue description
It starts successfully; detects changes successfully; but doesn't reload the page.

## Software details

* Command line used for launching `live-server`:
* OS: macOS 12.4
* Browser (if browser related): Firefox
* Node.js version: 18.7.0
* `live-server` version: 1.2.2

**Comment by aviraltiwari** [comment]
I'm facing same issue on WSL2

**Comment by proffapt** [comment]
> I'm facing same issue on WSL2

Did you have a proper html syntax? I mean html, title and body tag..


Because that's what I was missing at, and when i made sure it wasn't the case.. it worked.
