### ISSUE TITLE
Live-Server Ajax Call

### ISSUE THREAD

**Issue by jtang227** [tapio/live-server#40]
I am trying to get the json file and seems not working.

// js
```js
$(function() {

	var $orders = $('#orders');

	$.ajax({
		type: 'GET',
		url: '/api/orders.json',
		success: function(orders) {
			$.each(orders, function(i, order) {
				$orders.append('<li>name: '+ order.name + ', drink: '+ order.drink +'</li>');
			});
		},
		error: function() {
			console.log('Error!');
		}
	});
});
```

// json
```JSON
"orders":[
	{
		"id": 1,
		"name": "John",
		"drink": "Honey Green Tea"
	},
	{
		"id": 2,
		"name": "Will",
		"drink": "Taro Milk Tea"
	}
]
```

**Comment by harrytruong** [comment]
@jtang227 I'm having trouble understanding your issue. Could you update to the latest version, and if the issue still exists, then re-submit with a cleaned up issue description? See [Github Markdown docs](https://help.github.com/articles/github-flavored-markdown) for proper styling [especially the fenced-code-blocks section](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks).

My best guess is that your `orders.json` file is not located within an `/api` folder. Please check again?
