### ISSUE TITLE
Prevent script injection in an iframe

### ISSUE THREAD

**Issue by SirMetathyst** [tapio/live-server#400]
## Issue description
How to prevent script injection in an iframe

![image](https://user-images.githubusercontent.com/34924197/184361163-8a78142b-0bbd-44a1-a0a1-9d0e2c4cea11.png)

## Software details

* Command line used for launching `live-server`: live-server --no-css-inject
* OS: Linux
* Browser (if browser related): Brave
* Node.js version: 12.22.9
* `live-server` version: 1.2.2

**Comment by SirMetathyst** [comment]
Found solution: add head tag above body in srcdoc.

**Comment by filletofish** [comment]
@SirMetathyst, I think adding head tag above the doc does not prevent script injection into an iframe anymore. Have you found any other solutions?
