### ISSUE TITLE
custom 404 page is required so that we can mimic html5 enabled urls for angular.js

### ISSUE THREAD

**Issue by MContagious** [tapio/live-server#44]

**Comment by harrytruong** [comment]
Hey @MContagious, I've submitted PR https://github.com/tapio/live-server/pull/48 that enables this functionality. It would be something like:

```bash
$ live-server --entry-file=index.html
```

Would this fit your needs? Let me know if you have any feedback.

**Comment by MContagious** [comment]
That will suffice. Thanks for the quick turnaround.

**Comment by tapio** [comment]
`--entry-file` merged to master.
