### ISSUE TITLE
Watch filter or path

### ISSUE THREAD

**Issue by levithomason** [tapio/live-server#45]
Currently, the browser reloads on any file change in `root`.  It'd be nice to filter which files, or directories, were watched.  This way when I can point the watcher to my `dist` dir and only reload when that changes.  Right now, I get a reload when I change a `*.less` file and another after the build step builds the css.

I can do the PR if you like.  Love the simplicity, thanks.

**Edit**
Why not set the root to `dist`?  Because it's a doc page on `gh-pages` so the `index.html` is in the root of the project.

**Comment by evelynStraigt** [comment]
:+1:

I would also love this feature, I did a really quick and dirty implementation on my own just to try something out and it's exactly what I need.

**Comment by harrytruong** [comment]
:+1: I like the idea too, but could one of you guys submit a PR? Or document what exact behavior/flags you're referring to? I'm guessing it's something like:

```bash
$ live-server --watch=path,another/path
```
Where `--listen` is `.` by default, and can be a comma-separated string of paths.

**Comment by dotnetCarpenter** [comment]
@tapio @harrytruong  `--listen` is undocumented in the [README](/tapio/live-server#readme)

**Comment by arthurmuchir** [comment]
+1

**Comment by tapio** [comment]
There is `--ignore=path` which could probably achieve the desired effect, if the less files are in a directory which can be ignored as a whole.

**Comment by levithomason** [comment]
Pardon pseudo code, on my phone. Scanning the code (on my phone at least), looks like index.js at LiveServer.start() has this line 

var watchPaths = [root];

Where root is the server root or cwd. I think adding a - - watch-paths OPTION that took a comma separated list and using in in the above line something like: 

var watchPaths = options.watchPaths || [root] 

Would do the trick. Then you can serve from the root, but only reload when a certain directory changes.

This is preferred over ignoring because in this use case you would need to ignore many files and directories to get the same result. Also, some files and directories can be generated during run time making it more ambiguous what to ignore.

I can do a PR for the full and proper enhancement if you'd like this option added.

**Comment by levithomason** [comment]
Sorry about caps, phone typo!

**Comment by tapio** [comment]
Should probably think also about using watchr's `ignoreCustomPatterns` feature: might be nice to ignore e.g. all files that have .less/.scss extension.

**Comment by levithomason** [comment]
Less files were just an example use case.  The real fix here is targeting what to watch. For instance, it's common to have an app or src directory that has a build step that builds to a dist or build folder. There can be files of all types in both. The goal is, you only want to reload when the build / dist directory is updated, not based on file types. 

There are similar patterns to this feature in Webpack's loader config. You can 'exclude' patterns from being run through the loader, but you can also 'include' patterns. The include is the recommended approach in the docs because it is explicit. There is a finite and well defined list of things you want to parse opposed to an infinite list of things you want to exclude (everything else).

Babel has a similar option with its register hook. You can compile 'only' certain patterns or 'ignore'.  Or what if mocha had you ignore every directory that did not have tests in it?  

I guess what I'm getting at is that when you know exactly what you want to watch, it is easier and makes more sense to explicitly define it that  try to ignore every other possible thing.

That's my whole hearted attempt at a persuading you :) Whether the update makes it or not, still love the module and will probably keep using it.

**Comment by levithomason** [comment]
Thanks, super appreciated @tapio!
