### ISSUE TITLE
Can live-server be extended or embedded into a project with nodejs or java-ee as backend ?

### ISSUE THREAD

**Issue by pigerla** [tapio/live-server#56]
I know **live-server** works perfectly as a nodejs server via WebSocket.
But what if there is a web project with nodejs or java-ee as backend , I want to reload  or refresh files just like how live-server works. Is that possible ?

Besides, are there any tools or plugins can achieve this ?

**Comment by tapio** [comment]
Live-server is pretty small, so adapting it's code to an existing node.js server should be pretty easy. Other languages are of course more work as the js code and possibly many of the dependencies need to be ported.

I haven't tested, but it might also be possible to only make your backend do injecting of the script snippet and then have a live-server instance that handles the file watching and websocket communication.
