### ISSUE TITLE
Live reload with index.jade

### ISSUE THREAD

**Issue by michaeljoshua55555** [tapio/live-server#57]
Hi, 

I am using jade in my project, I don't have index.html. I have index.jade

The documentation said that I need to have index.html

can I use live server in my project ?

**Comment by tapio** [comment]
I have no idea how jade works. Apparently it's some kind of templating thingy? If it generates static html out of .jade files, you can server the static files and live reload will work every time you regenerate the html files.

If html is generated from jade on the fly and served by a special server app, then it won't work. However, if the jade server is also made with node.js, you might be able to adapt and integrate code from live-server to gain the functionality. If the server is third-party, it's also worth checking if it already provides similar functionality.
