### ISSUE TITLE
live-server not starting server

### ISSUE THREAD

**Issue by rajakvk** [tapio/live-server#59]
I have been using live-server package for past few months without any trouble. When I try to invoke server with "live-server" today, received following error
live-server is not recognized as an internal or external command, operable program or batch file.
npm update -g live-server - no luck
npm uninstall -g live-server and npm install -g live-server - no luck
npm install live-server - no luck ( installing at local directory)
node c:\Users\xxxx\AppData\Roaming\npm\node_modules\live-server\live-server - works fine.
It seems that node path path is not automatically added to environment variable.
I'm on Windows 7 64 bit.

**Comment by tapio** [comment]
Do other globally installed npm programs work? This seems more like an npm issue than live-server issue...
