### ISSUE TITLE
live-server has stopped detecting file changes

### ISSUE THREAD

**Issue by jkyoutsey** [tapio/live-server#61]
This was working on my system and now is not.  I have live-server version 0.8.1 installed globally.

    npm install live-server -g

But when I start it I don't get the "Live Reload Enabled" message in the browser console and it doesn't detect file changes anymore.

I've uninstalled it completely and re-installed it to no avail.

The http server is working.  It will serve up my index.html and all related content.  It just won't detect file changes.

Starting live-server:

    live-server --open=src

I'm using typescript outputting js to src/dist/...  I've verified that the file is changing.  I can modify the js directly as well.  In no case does live-server detect any changes.

**Comment by jkyoutsey** [comment]
I would delete this issue if I could see how.  Appears to have been a Chrome issue.  After trying in Safari it was working, then back to Chrome and it started working.

**Comment by shuaibird** [comment]
I come across the same problem now. It doesn't work for Neither Safari nor Chrome. If you know how to fix it, plz let me know.

**Comment by tapio** [comment]
Where are the files you are trying to reload? At some point I noticed the reload didn't work in `/tmp` for some reason.

**Comment by shuaibird** [comment]
I used the same dir that used to work but it just didn't work. I try using another dir, it works! the latter one is just inside the prev one. Quite weird

**Comment by tbertenshaw** [comment]
I've just had the same issue. Was working nicely in chrome, now its stopped working.

**Comment by SteveAtSentosa** [comment]
same for me
