### ISSUE TITLE
localhost instead of 127.0.0.1

### ISSUE THREAD

**Issue by jeroencusters** [tapio/live-server#66]
Is it possible to open the browser with localhost instead of 127.0.0.1? 
I tried 'live-server --host=localhost' but this doesn't work.

**Comment by mattborn** [comment]
:+1:

**Comment by tapio** [comment]
It was `localhost` first, but it had problems (see #7). Apparantly there is no one address that works properly everywhere. :(

**Comment by mattborn** [comment]
@tapio I get that different environments (OS and browsers) and use cases (http server, websockets, livereload, etc.) each have their own concerns and limitations so it’s prudent to provide a sane default, but I think this issue suggests an explicit `host` value should not be converted back to one of the defaults (either `127.0.0.1` or `0.0.0.0`). It should be considered a bug if setting a `host` value either in the command-line or in the `.live-server.json` doesn’t work.

**Comment by tapio** [comment]
The code used the resulting IP address of the given host string as the open url. I've now changed it in c94694bd5eb95 to use the user supplied string so that `live-server --host=localhost` really opens the browser at literally the string "localhost".

**Comment by mattborn** [comment]
@tapio :heart:
