### ISSUE TITLE
live-server not starting server

### ISSUE THREAD

**Issue by Cabarfeidh** [tapio/live-server#68]
Hi,
I just can't seem to get live-server to open up a browser. It just seems to 'hang' at the command prompt.
I have the following setup:
Microsoft Windows: 10.0.10240
WebStorm: 11.0.1
Node: 4.2.1
NPM: 3.3.8.
I have tried installing globally and locally. I have tried using npm and the 'manual' installations. Everything else I install using these methods works ok.
Anyone have any ideas what if anything could be causing a conflict?
Many thanks for the effort put into this project.

**Comment by tapio** [comment]
Are you giving live-server any parameters? Is this only an issue with opening the page in a web browser, i.e. does the server work and serve pages if you type `127.0.0.1:8080` manually into your browser's address bar?
