### ISSUE TITLE
SCSS & Compass

### ISSUE THREAD

**Issue by reisnobre** [tapio/live-server#69]
Hey guys

I'm having some trouble with Live-Server, I'm using Compass to compile the Scss to regular CSS and the Live-Server is going nuts trying to reload when I save the SCSS file and when the Compass rewrite the CSS file, there's a way to make Live-Server don't look for SCSS files?

**Comment by tapio** [comment]
Do you have the scss files in a separate directory? If so, you could use the `--ignore=path/to/scss/files` option.

**Comment by tapio** [comment]
There's now also `--ignorePattern=RGXP` param you can use to exclude stuff based on e.g. file extension.
