### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by inadarei** [tapio/live-server#7]
Getting this in the console:

```
WebSocket connection to 'ws://localhost:8080//ws' failed: Connection closed before receiving a handshake response
```

OS X Yosemite, Google Chrome (latest)

**Comment by inadarei** [comment]
I was able to pinpoint this to index.js using "localhost". When I replaced `localhost` with 127.0.0.1 (or: `0.0.0.0` to indicate "any local interface") – things worked perfectly.

With localhost, websockets and livereload never works but even just opening the page with a browser stops working intermitently (quite often). Not sure what the problem is since localhost is properly configured in /etc/hosts, but the problem is real.

Will open a pull request with the fix

**Comment by simplesmiler** [comment]
This is most likely related to ipv4/ipv6.
