### ISSUE TITLE
Can not open .svg file

### ISSUE THREAD

**Issue by dotnetCarpenter** [tapio/live-server#70]
I've tried with `live-reload map.svg`, `live-reload ./map.svg` and `live-reload --entry-file map.svg` both give me the same error:
```
Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (C:\Users\dotnet\AppData\Roaming\npm\node_modules\live-server\live-server.js:82:10)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

I then made an index.html which redirects to map.svg but then there is no live reload.
```html
<script>
  location.replace("map.svg");
</script>
```

OS: Windows7
node: v5.1.0
npm: 3.5.0

**Comment by dotnetCarpenter** [comment]
After reading the [source](https://github.com/tapio/live-server/blob/master/live-server.js#L82), I think there is a fundamental flaw in the logic. The workaround is to do `live-server ./ map.svg`.

`live-reload ---help` states that `Usage: live-server [-v|--version] [-h|--help] [-q|--quiet] [--port=PORT] [--host=HOST] [--open=PATH] [--no-browser] [--ignore=PATH] [--entry-file=PATH] [--wait=MILLISECONDS] [PATH]`. Here [PATH] is supposedly the path to the file you want to open. But as we just saw, that doesn't work. The argument is passed to [`process.chdir`](http://devdocs.io/node/process#process_process_chdir_directory) which expect only a path to a directory.

BTW, still no live reload.

**Comment by dotnetCarpenter** [comment]
The fix for live reload in a svg document is to inject the websocket in this:
```xml
<script type="application/ecmascript">
  <![CDATA[
    websocket code here...
  ]]>
</script>
```

**Comment by dotnetCarpenter** [comment]
Here is the culprit: https://github.com/tapio/live-server/blob/master/index.js#L63

**Comment by tapio** [comment]
Let's discuss in #71.

**Comment by dotnetCarpenter** [comment]
@tapio cool
