### ISSUE TITLE
live server held directory after git removed it (on windows 10)

### ISSUE THREAD

**Issue by abendigo** [tapio/live-server#73]
this was kind of a wierd error, and I don't expect it to get fixed, but I am documenting it here in case any one else runs into it.

on windows 10 (ya, I know, get a real OS.. lol), I had added a new directory, and a new file inside that directory, which live server dutifly served up. But then I needed to do a git rebase, so git removed that folder, did some other things, then tried to add it back again. Unfortunately, it could not.

When I tried to manually delete the folder after (with live server still running), it looked like the folder had no owner. It was only when I finally shut down liver server that the directory was removed.

**Comment by tapio** [comment]
Closing, but let me know if you run into this repeatedly and think there is something I could do in live-server side.
