### ISSUE TITLE
Only reload on files that are in use in the browser

### ISSUE THREAD

**Issue by Industrial** [tapio/live-server#76]
Hi.

I use `gulp` with `babel`,`browserify` and `live-server`.

1. I change a .js file.
2. Babel.js compiles the file from src/ to build/.
3. live-server reloads the browser for a file that is NOT used.
4. Browserify compiles all the client side JS to 1 file.
5. live-server reloads again for js/app.bundle.js which IS used.

**Comment by Industrial** [comment]
[gulp-sane-watch] 1 file changed (client/js/reducers.js)
[15:34:03] Starting 'compileBabel'...
[15:34:03] Finished 'compileBabel' after 59 ms
File change detected
[15:34:07] 2311829 bytes written (3.41 seconds)
File change detected

**Comment by tapio** [comment]
You can use `--ignore` and/or the new `--ignorePattern` parameters to exclude stuff from file watcher.

**Comment by Industrial** [comment]
That would mean I'd have to explicitly configure files/paths for every project, while I've setup my gulp project/setup to compile "whatever is there" with babel/less/etc. I've moved on from browser page reloading to hot module reloading for this reason.

**Comment by tapio** [comment]
Just for reference, there is now also `--watch=PATH,PATH2` param, which can be used to specify what files to watch ignoring everything else. So possibly something like `live-server --watch=build` could work in your case, though individually hotloadable js modules sound much better.

**Comment by kylecordes** [comment]
It seems to me that these various configurable watch and ignore options are missing the point. Live-server already has all of the information it needs to know what to watch: it knows exactly what files have been fetched by the browser. Why would anyone want to explicitly configure these files instead of using this information already present?
