### ISSUE TITLE
why would report 502 errors

### ISSUE THREAD

**Issue by huoqishi** [tapio/live-server#79]
npm install -g live-server
live-server

on windows10
The following is a detailed error
------------------------------------------------------
502 Server dropped connection

The following error occurred while trying to access http://localhost/test.html:

502 Server dropped connection

Generated Sat, 09 Jan 2016 06:33:50 GMT by Polipo on DESKTOP-4TOPUNE:8123.

**Comment by tapio** [comment]
Haven't seen that before. I'd start checking that it's not caused by firewall or some proxy / funky network configuration.
