### ISSUE TITLE
--ignore regex

### ISSUE THREAD

**Issue by coreyog** [tapio/live-server#80]
I'm working with a typescript project that compiles my ts files in-place. I'm using live-server to view all the html and generated js files. I would love to use --ignore=*.ts or --ignore=**/*.ts to not refresh the browser when a ts file is updated. The typescript compiler will update the js files then live-server will notice those changes and update accordingly. Right now the browser refreshes twice (once for the ts file change, again when tsc finishes compiling js files). I could try to set --wait to a long enough value but that will be hit or miss depending on compile time.

I would still like the file to be served to the browser. Typescript projects can generate .js.map files so debugger statements/breakpoints highlight the proper ts line when triggered. But I don't want the browser to refresh when my ts files are updated because soon more files are about to update. It would be an ongoing pain to list them all individually.

watchr has a property called ignoreCustomPatterns so I don't imagine this change to have a large impact. Maybe a --ignorePattern= flag that gets passed along to that parameter?

**Comment by pdeva** [comment]
+1

**Comment by tapio** [comment]
`--ignorePattern` is commited to master.

**Comment by pdeva** [comment]
when do you plan to make a release with it?

On Wednesday, January 20, 2016, Tapio Vierros <notifications@github.com>
wrote:

> Closed #80 <https://github.com/tapio/live-server/issues/80>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tapio/live-server/issues/80#event-520957163>.
>


-- 
Prashant

**Comment by tapio** [comment]
Perhaps tommorow if I don't forget.
