### ISSUE TITLE
Failed to inject refresh script! Couldn't find any of the tags  [ '</body>', '</svg>' ]

### ISSUE THREAD

**Issue by kemalcany** [tapio/live-server#85]
Hello guys,

When using live-server with html templates that contain only parts of a code (for example just a simple <p>{variable}</p> tag), this warning gets shot on the server cause there is no body or svg candidate. And therefore a lot of non-critical warning messages comes out. 

Setting the quiet option parameter to live-server doesn't stop this. 

Could it be covered by the quiet option? Or a new parameter? Or do you think this is an important message that shouldn't be stopped?

Cheers!

**Comment by tapio** [comment]
`--quiet` should indeed suppress it. For reference, the message was added in #75.

**Comment by talmog** [comment]
How can we pass the quiet option if not using the console (using node)?

**Comment by tapio** [comment]
Pass `logLevel: 0` among other params you use to start live-server.

**Comment by talmog** [comment]
thank you, but that didn't silent the errors mentioned here.

**Comment by kemalcany** [comment]
#88 pull request has the fix for this bug.

**Comment by tapio** [comment]
I'll dedicate some time for fixes once I'm back from a vacation in a few days.

**Comment by talmog** [comment]
oh I see, thank you very much!

**Comment by kemalcany** [comment]
you totally deserve it mate :) enjoy!
