### ISSUE TITLE
`root` option from command line?

### ISSUE THREAD

**Issue by mhkeller** [tapio/live-server#89]
Am I missing something or is the ability to specify a root not available via the cli? I see the `--open` option but if I am serving out of a `public/` folder, my paths will need to start with `/public` instead of `/`.

It seems I could set it in `~./live-server.json` but I would prefer to keep settings on a per-project basis.

**Comment by tapio** [comment]
`live-server public` or `cd public && live-server`

**Comment by mhkeller** [comment]
Got it. Thanks.

**Comment by HongJheLi** [comment]
@tapio  Thanks for your tips.
