### ISSUE TITLE
Failed to inject refresh script!

### ISSUE THREAD

**Issue by KevinBurton** [tapio/live-server#97]
I am getting an error/warning like:
Failed to inject refresh script! Couldn't find any of the tags  [ '</body>', '</
svg>' ] from <...>
I am not sure what this message means. Any suggestions?

**Comment by tapio** [comment]
It means the server is serving you an html file but cannot find </body> tag, which means the live-reload won't work for that particular file.

**Comment by mariocatch** [comment]
@tapio Is it supposed to still work with component-based web frameworks, like Angular Components, React, etc? There's no `body` tag in those so live-reload won't inject itself it seems.

**Comment by ShadOoW** [comment]
it should try to find body tag only on entry file not on every html element.

**Comment by tapio** [comment]
@mariocatch Can you give an example about what that kind of index.html (or similar) looks like? Generally speaking live-server determines files to inject primarily based on file extension and then it tries to find <body> because we don't want to inject every .html file blindly - some of them could be "includes" that are fetched separately and would then cause multiple injects on the final page. If you have ideas on how to handle this better, please do tell.

**Comment by ShadOoW** [comment]
@tapio I don't know much about other use cases where the existing behavior may be needed or expected, I've personally always assumed livereload => index file)

In my actual use case single page app with angular2, only entry file should be injected, right now the only way to silence those errors is to reduce the log output ```logLevel: 1```.

live-server has two options that could be used to mean this: ```[--entry-file=PATH] [--spa]```
an example of spa: http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

cheers.

**Comment by tapio** [comment]
Perhaps the warning should just be removed as it's causing confusion. <body> is used for a) detecting which files are actual pages and not some include fragments and b) where to inject the script so that it doesn't trigger any quirks mode.

**Comment by ShadOoW** [comment]
+1, also a compromise could be to throw error if 0 body are detected, as long as body detected > 1, then it probably working as expected.

**Comment by kylecordes** [comment]
By the way, live-server is pretty popular in the Angular community so many many developers are now seeing the spurious messages. So far the only way I've seen to make them go away is with the option to be completely quiet, that silences other useful messages also. I think the idea above to remove the warning might be the best answer.  Serving a page fragment with the name *.html is very common.
